name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100

    - name: Install dependencies
      run: dotnet restore

    - name: Install tools
      run: dotnet tool install --global coverlet.console

    - name: Build Release
      run: dotnet build --configuration Release --no-restore

    - name: Build Debug
      run: dotnet build --configuration Debug --no-restore

    - name: Testing FizzBuzz.Core Library
      run: coverlet FizzBuzz/FizzBuzz.Core.UnitTests/bin/Debug/netcoreapp3.0/FizzBuzz.Core.UnitTests.dll --target "dotnet" --targetargs "test FizzBuzz/FizzBuzz.Core.UnitTests/FizzBuzz.Core.UnitTests.csproj --no-build --verbosity quiet" --format OpenCover --output fizzbuzz.core.coverage.xml

    - name: Testing BowlingGame.Core Library
      run: coverlet BowlingGame/BowlingGame.Core.UnitTests/bin/Debug/netcoreapp3.0/BowlingGame.Core.UnitTests.dll --target "dotnet" --targetargs "test BowlingGame/BowlingGame.Core.UnitTests/BowlingGame.Core.UnitTests.csproj --no-build --verbosity quiet" --format OpenCover --output bowlinggame.coverage.xml

    - name: Testing Wardrobe.Core Library
      run: coverlet Wardrobe/Wardrobe.Core.UnitTests/bin/Debug/netcoreapp3.0/Wardrobe.Core.UnitTests.dll --target "dotnet" --targetargs "test Wardrobe/Wardrobe.Core.UnitTests/Wardrobe.Core.UnitTests.csproj --no-build --verbosity quiet" --format OpenCover --output wardrobe.coverage.xml

    - name: Testing TicTacToe.Core Library
      run: coverlet TicTacToe/TicTacToe.Core.UnitTests/bin/Debug/netcoreapp3.0/TicTacToe.Core.UnitTests.dll --target "dotnet" --targetargs "test TicTacToe/TicTacToe.Core.UnitTests/TicTacToe.Core.UnitTests.csproj --no-build --verbosity quiet" --format OpenCover --output tictactoe.coverage.xml

    - name: Testing PasswordVerifier.Core Library
      run: coverlet PasswordVerifier/PasswordVerifier.Core.UnitTests/bin/Debug/netcoreapp3.0/PasswordVerifier.Core.UnitTests.dll --target "dotnet" --targetargs "test PasswordVerifier/PasswordVerifier.Core.UnitTests/PasswordVerifier.Core.UnitTests.csproj --no-build --verbosity quiet" --format OpenCover --output passwordverifier.coverage.xml

    - name: Testing ScoreKeeper.Core Library
      run: coverlet ScoreKeeper/ScoreKeeper.Core.UnitTests/bin/Debug/netcoreapp3.0/ScoreKeeper.Core.UnitTests.dll --target "dotnet" --targetargs "test ScoreKeeper/ScoreKeeper.Core.UnitTests/ScoreKeeper.Core.UnitTests.csproj --no-build --verbosity quiet" --format OpenCover --output scorekeeper.coverage.xml

    - name: Testing MarsRover.Core Library
      run: coverlet MarsRover/MarsRover.Core.UnitTests/bin/Debug/netcoreapp3.0/MarsRover.Core.UnitTests.dll --target "dotnet" --targetargs "test MarsRover/MarsRover.Core.UnitTests/MarsRover.Core.UnitTests.csproj --no-build --verbosity quiet" --format OpenCover --output marsrover.coverage.xml


    - name: Upload
      run: bash <(curl -s https://codecov.io/bash)
